import { Paper, Title, Text, Group, Stack, RingProgress, SimpleGrid, Card, Image, Box, Badge } from '@mantine/core';
import type { SteamGame } from '@/lib/steam';
import type { GameReview } from '@/store/useReviewStore';
import { IconTrophy, IconClock, IconDeviceGamepad2 } from '@tabler/icons-react';
import { forwardRef } from 'react';

interface SummaryData {
    user: { name: string; image: string };
    totalGames: number;
    totalPlaytime: number; // minutes
    beatenCount: number;
    droppedCount: number;
    playedCount: number;
    topGames: (SteamGame & { rating: number })[];
}

interface SummaryCardProps {
    data: SummaryData;
}

export const SummaryCard = forwardRef<HTMLDivElement, SummaryCardProps>(({ data }, ref) => {
    const hours = Math.round(data.totalPlaytime / 60);

    return (
        <Paper
            ref={ref}
            p="xl"
            radius="lg"
            bg="var(--mantine-color-dark-8)"
            style={{ maxWidth: 800, margin: '0 auto', border: '1px solid var(--mantine-color-dark-4)' }}
        >
            <Stack gap="xl">
                {/* Header */}
                <Group justify="space-between" align="center">
                    <Stack gap={0}>
                        <Title order={1} c="blue.4">YEAR IN REVIEW</Title>
                        <Text size="xl" fw={700} c="white">{data.user.name}</Text>
                    </Stack>
                    {/* Avatar could go here but cross-origin issues with html-to-image might happen if not proxy. Avoiding for now or hoping Next/Image handles it. */}
                    {/* Using a simple trophy icon instead to be safe from CORS for now. Steam avatars are strict. */}
                    <IconTrophy size={64} color="gold" />
                </Group>

                {/* Key Stats */}
                <SimpleGrid cols={3}>
                    <Card bg="dark.6" radius="md" p="md">
                        <Stack align="center" gap="xs">
                            <IconClock size={32} color="var(--mantine-color-blue-4)" />
                            <Text size="xs" c="dimmed" tt="uppercase" fw={700}>Time Played</Text>
                            <Title order={2}>{hours}h</Title>
                        </Stack>
                    </Card>
                    <Card bg="dark.6" radius="md" p="md">
                        <Stack align="center" gap="xs">
                            <IconDeviceGamepad2 size={32} color="var(--mantine-color-green-4)" />
                            <Text size="xs" c="dimmed" tt="uppercase" fw={700}>Games Played</Text>
                            <Title order={2}>{data.totalGames}</Title>
                        </Stack>
                    </Card>
                    <Card bg="dark.6" radius="md" p="md">
                        <Stack align="center" gap="xs">
                            <IconTrophy size={32} color="var(--mantine-color-yellow-4)" />
                            <Text size="xs" c="dimmed" tt="uppercase" fw={700}>Completed</Text>
                            <Title order={2}>{data.beatenCount}</Title>
                        </Stack>
                    </Card>
                </SimpleGrid>

                {/* Top Games */}
                {data.topGames.length > 0 && (
                    <Box>
                        <Title order={3} mb="md" ta="center">Top Rated Games</Title>
                        <SimpleGrid cols={3}>
                            {data.topGames.map(game => (
                                <Card key={game.appid} padding="sm" radius="md" bg="dark.6">
                                    <Card.Section>
                                        <Image
                                            src={`https://cdn.cloudflare.steamstatic.com/steam/apps/${game.appid}/header.jpg`}
                                            height={100}
                                            fallbackSrc="https://placehold.co/600x400"
                                        />
                                    </Card.Section>
                                    <Stack mt="sm" gap={4} align="center">
                                        <Text fw={600} lineClamp={1} size="sm">{game.name}</Text>
                                        <Badge color="yellow" variant="filled">
                                            {game.rating}/10
                                        </Badge>
                                    </Stack>
                                </Card>
                            ))}
                        </SimpleGrid>
                    </Box>
                )}

                {/* Footer */}
                <Text size="xs" c="dimmed" ta="center">Generated by Rei Steam Year</Text>
            </Stack>
        </Paper>
    );
});

SummaryCard.displayName = 'SummaryCard';
